### PR TITLE
3.x<

### PR DESCRIPTION
**Pull request by kuhnchris**

### CODE REVIEW

**Comment by akien-mga** [comment]
Hello @kuhnchris!

Would it be possible for you to close this PR? It's not the proper workflow to update your fork's branch with the Godot repository, and it creates backreferences for all these commits linking to your PR.

See e.g. https://github.com/godotengine/godot/commit/92664f03a921b1e5bc07e54b00d4ef9d4acfc7b9
image

GitHub is to blame for even linking to thirdparty forks at this level, but the only way to solve it is for you to close this PR.

**Comment by kuhnchris** [comment]
Hey there @akien-mga - want me to close and *reopen* it or just close and discard in it's entirety?

edit: nevermind, I just close this one, sorry.

And, i remember now, i tried to close it but it need to do some git magic on the command line, as github basically threw it's hand up and said "not my issue"

image

**Comment by akien-mga** [comment]
That's the button for merging, but you should have a button to actually close (without merging).

This can't be merged as there are 2,511 commits conflicting with your branch, it's not a valid PR.

**Comment by kuhnchris** [comment]
Nevermind i'm being stupid, sorry. If something like that is happening feel free to ping me over on discord - i'm usually around, my bad. Closed to void spaming hundreds of people involved.

**Comment by akien-mga** [comment]
Thanks!

**Pull request closed without merging**
